[package]
name = "meow"
version = "0.1.0"
authors = ["Julian Zhang <zhangchunzhong@gmail.com>"]
edition = "2018"

[dependencies]
clap = { version = "2.33.0", optional=true }

 [features] 
yaml=["clap"]